name: para_new
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pinput: ^0.1.10
  shared_preferences: ^0.5.6+2
  http: ^0.12.0+4
  image_picker: ^0.6.3+4
  file_picker: ^1.4.3+2
  cupertino_icons: ^0.1.3
  smooth_star_rating: ^1.0.4+2
  toast: ^0.1.5
  easy_localization: ^2.0.0
  intl: ^0.16.0
  table_calendar: ^2.2.3
dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - lang/